name = "SMP 6 - Conventional Wisdom"
author = "enjarai"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "41c8a7925fc481a33f8f36aba70d4ea8b237116c3153fb783c054988de973d1b"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
